name: oceanstream
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jinja2
  - netcdf4
  - numpy
  - pytz
  - scipy
  - pandas
  - s3fs
  - requests
  - aiohttp
  - geopy
  - flake8
  - isort
  - dask
  - dask-image
  - pynmea2
  - xarray
  - zarr
  - fsspec
  - psutil>=5.9.1
  - more-itertools==8.13.0
  - pydantic>2
  - echopype
  - haversine
  - black
  - bottleneck
  - check-manifest
  - codespell
  - docker-compose
  - flake8-builtins
  - flake8-comprehensions
  - flake8-mutable
  - flake8-print
  - mypy
  - numpydoc
  - pre-commit
  - pylint
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-xdist
  - setuptools_scm
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid
  - twine
  - wheel
  - pip
  - git
  - pip:
      - git+https://github.com/OceanStreamIO/echopype.git@next-dev
